# Generated by Django 4.0 on 2022-01-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_alter_fib_question_user_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_question',
            name='Five',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mc_question',
            name='Four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mc_question',
            name='Three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
