# Generated by Django 4.0.1 on 2022-01-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0007_tf_question_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_question',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam.assignment'),
        ),
    ]
